Feature/cards
skaamoogs/react-intensive pull request #29
Opened 2024-02-11 05:32 UTC by astafa98

![bandicam 2024-02-11 08-22-51-021](https://github.com/skaamoogs/react-intensive/assets/112830586/72d8e7ce-f6a3-4165-927e-2e42b386f518)

2024-02-11 10:55 UTC, skaamoogs requested changes

2024-02-11 10:55 UTC, skaamoogs commented on src/components/filmcard/FilmCard.tsx
> +          src='https://m.media-amazon.com/images/M/MV5BMjE2NDkxNTY2M15BMl5BanBnXkFtZTgwMDc2NzE0MTI@._V1_.jpg'
Давай сразу пропсами передавать все данные: name, imageSrc и т.д

2024-02-11 11:08 UTC, astafa98 reviewed
+

2024-02-13 08:23 UTC, analsituation approved these changes

2024-02-13 08:25 UTC, analsituation approved these changes

2024-02-13 17:26 UTC, astafa98 commented on src/components/filmcard/FilmCard.tsx
> +          src='https://m.media-amazon.com/images/M/MV5BMjE2NDkxNTY2M15BMl5BanBnXkFtZTgwMDc2NzE0MTI@._V1_.jpg'
Сегодня доделаю

2024-02-14 05:10 UTC, skaamoogs approved these changes

2024-02-14 14:47 UTC, merged